Auth state (#39)
* Added protected pages and auth

* updated report reducers & actions

On report submit

TypeError: firebase.database is not a function

* Updated report reducer and action

Error: Firebase does not update on push, no errors indicated

* Update reportActions.js

* updated report contents

* Update Login.js

* Fixed some merge conflicts

Co-authored-by: Rkuangdev <RKuangDev@gmail.com>